import styles from '@/styles/general';

export const weeklyVolumeData = [
        {   
            name:"chest",
            population:17,
            color:"#ff9933",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },
        {   
            name:"back",
            population:17,
            color:"#bfbfbf",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },
        {   
            name:"shoulders",
            population:16,
            color:"#ffd9b3",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },
        {   
            name:"quads",
            population:11,
            color:"#b35900",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },
        {   
            name:"hamstrings",
            population:11,
            color:"#331a00",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },
        {   
            name:"biceps",
            population:10,
            color:"#4da6ff",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },
        {   
            name:"triceps",
            population:14,
            color:"#004d99",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },
        {   
            name:"abs",
            population:5,
            color:"#cce6ff",
            legendFontColor:styles.baseText.color,
            legendFontSize:12
        },    
    ];